---
- name: Install Nodejs
  package:
    name: nodejs
    state: present
  tags:
    - deploy
- name: Install Bower
  npm:
    path: /home/{{ app_user_name }}/app/{{ git_repo }}
    name: bower

- name: Updating packages based on package.json to their latest version.
  npm:
    path: /home/{{ app_user_name }}/app/{{ git_repo }}
    state: latest
  tags:
    - deploy

- name: Install packages based on bower.json.
  bower:
    path: /home/{{ app_user_name }}/app/{{ git_repo }}