---
- name: Check if skymanager.service is registered in systemd
  stat:
    path: /etc/systemd/system/skymanager.service
  register: file_details
  tags:
    - deploy
- name: Templating skymanager_service.j2 to register skymanager service
  template:
    src: skymanager_service.j2
    dest: /etc/systemd/system/skymanager.service
    owner: "{{ app_user_name }}"
    mode: "0755"
- name: Templating skymanager_env.j2 to register .env file
  template:
    src: skymanager_env.j2
    dest: /home/{{ app_user_name }}/app/{{ git_repo }}/.env
    owner: "{{ app_user_name }}"
    mode: "0755"
  tags:
    - deploy
  when: not file_details.stat.exists
-  name: Trigger Daemon-reload, Restart skymanager.service
   command: /bin/true
   notify: Daemon-reload, Restart skymanager.service
   tags:
    - deploy
