---
- name: Provision the VPC
  ec2_vpc_net:
    state: present
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
    multi_ok: no
    name: "{{ vpc_prefix }}_VPC"
  register: vpc_data
- name: Provision the subnet
  ec2_vpc_subnet:
    state: present
    region: "{{ aws_region }}"
    az: "{{ aws_az }}"
    cidr: "{{ vpc_subnet_cidr }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_subnet"
  register: subnet_data
- name: Provision the Internet Gateway
  ec2_vpc_igw:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    tags:
      Name: "{{ vpc_prefix }}_gw"
  register: igw_data
- name: Provision the Routing Table
  ec2_vpc_route_table:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_data.vpc.id }}"
    subnets:
      - "{{ subnet_data.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_data.gateway_id }}"
    tags:
      Name: "{{ vpc_prefix }}_rtbl"
  register: rtbl_data
- name: Provision the Security Group
  ec2_group:
    description: SSH and HTTP rules for instance
    state: present
    name: "{{ vpc_prefix }}_SecGroup"
    vpc_id: "{{ vpc_data.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: "{{ secgroup_ssh_allowed_instructor_cidr }}"
        rule_desc: Allow SSH from BCIT IP address
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow all internet to access
  register: secgroup_data